import { setLanguage } from '../i18n/language'
import { render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import Header from './Header'

beforeEach(() => setLanguage('vi'))
afterEach(() => vi.unstubAllGlobals())

it('keeps the closed mobile sheet inaccessible and returns keyboard focus on Escape', async () => {
  vi.stubGlobal('matchMedia', () => ({ matches: true, addEventListener() {}, removeEventListener() {} }))
  const user = userEvent.setup()
  render(<Header auth={{}} openAuth={vi.fn()} route="profiles/junior" />)
  const toggle = screen.getByRole('button', { name: 'Mở menu' })
  expect(screen.queryByRole('navigation')).not.toBeInTheDocument()
  expect(document.getElementById('main-nav')).toHaveAttribute('inert')
  toggle.focus()
  await user.keyboard('{Enter}')
  await waitFor(() => expect(screen.getByRole('link', { name: 'Phòng thu' })).toHaveFocus())
  await user.keyboard('{Tab}')
  const archive = screen.getByRole('button', { name: 'Kho lưu trữ' })
  expect(archive).toHaveFocus()
  expect(archive).toHaveAttribute('aria-expanded', 'false')
  await user.keyboard('{Enter}')
  expect(screen.getByRole('link', { name: 'Hồ sơ' })).toHaveAttribute('aria-current', 'page')
  await user.keyboard('{Escape}')
  expect(toggle).toHaveFocus()
  expect(toggle).toHaveAttribute('aria-expanded', 'false')
  expect(screen.queryByRole('navigation')).not.toBeInTheDocument()
  expect(document.getElementById('main-nav')).toHaveAttribute('inert')
})

it('groups existing routes and marks the active Archive page', async () => {
  const user = userEvent.setup()
  render(<Header auth={{}} openAuth={vi.fn()} route="profiles/junior" />)
  const nav = screen.getByRole('navigation')
  expect(within(nav).getByRole('link', { name: 'Phòng thu' })).toHaveAttribute('href', '#/studio')
  await user.click(within(nav).getByRole('button', { name: 'Kho lưu trữ' }))
  expect(within(nav).getByRole('link', { name: 'Hồ sơ' })).toHaveAttribute('aria-current', 'page')
  expect(within(nav).getByRole('link', { name: 'Dòng thời gian tinh tú' })).toHaveAttribute('href', '#/timeline')
  await user.keyboard('{Escape}')
  expect(within(nav).getByRole('button', { name: 'Kho lưu trữ' })).toHaveFocus()
  expect(within(nav).getByRole('button', { name: 'Kho lưu trữ' })).toHaveAttribute('aria-expanded', 'false')
  await user.click(within(nav).getByRole('button', { name: 'Cộng đồng' }))
  expect(within(nav).getByRole('link', { name: 'Góc người hâm mộ' })).toHaveAttribute('href', '#/projects')
  expect(within(nav).getByRole('link', { name: 'Bức tường giai điệu' })).toHaveAttribute('href', '#/wall')
})

it('defaults to Vietnamese and switches navigation and utilities to English without changing panel IDs', async () => {
  const user = userEvent.setup()
  render(<Header auth={{}} openAuth={vi.fn()} route="profiles/junior" />)
  const language = screen.getByRole('combobox', { name: 'Ngôn ngữ' })
  expect(language).toHaveValue('vi')
  expect(screen.getByRole('link', { name: 'JuniorMark — Trang chủ' })).toBeInTheDocument()
  await user.click(screen.getByRole('button', { name: 'Kho lưu trữ' }))
  expect(screen.getByRole('button', { name: 'Kho lưu trữ' })).toHaveAttribute('aria-controls', 'nav-Archive')
  expect(screen.getByRole('link', { name: 'Hồ sơ' })).toHaveAttribute('aria-current', 'page')
  await user.selectOptions(language, 'en')
  expect(screen.getByRole('combobox', { name: 'Language' })).toHaveValue('en')
  expect(document.documentElement).toHaveAttribute('lang', 'en')
  expect(screen.getByRole('link', { name: 'JuniorMark — Home' })).toBeInTheDocument()
  expect(screen.getByRole('button', { name: 'Archive' })).toHaveAttribute('aria-controls', 'nav-Archive')
  expect(screen.getByRole('link', { name: 'Profiles' })).toHaveAttribute('aria-current', 'page')
  expect(screen.getByRole('button', { name: 'Sign in' })).toBeInTheDocument()
  expect(screen.queryByRole('button', { name: 'Kho lưu trữ' })).not.toBeInTheDocument()
  await user.selectOptions(language, 'vi')
  expect(screen.getByRole('button', { name: 'Kho lưu trữ' })).toHaveAttribute('aria-expanded', 'true')
})

it('keeps account, Jummo and sign-in reachable in the mobile menu', async () => {
  vi.stubGlobal('matchMedia', () => ({ matches: true, addEventListener() {}, removeEventListener() {} }))
  const user = userEvent.setup(), openAuth = vi.fn()
  render(<Header auth={{}} openAuth={openAuth} />)
  await user.click(screen.getByRole('button', { name: 'Mở menu' }))
  const nav = screen.getByRole('navigation', { name: 'Điều hướng chính' })
  expect(within(nav).getByRole('link', { name: 'Quỹ đạo của tôi' })).toHaveAttribute('href', '#/orbit')
  expect(within(nav).getByRole('link', { name: 'Jummo' })).toHaveAttribute('href', '#/jummo')
  await user.click(within(nav).getByRole('button', { name: 'Đăng nhập' }))
  expect(openAuth).toHaveBeenCalledWith('signin')
  expect(screen.queryByRole('navigation')).not.toBeInTheDocument()
})
