import { readFile, writeFile } from 'node:fs/promises'

// Cùng một snapshot cho bản xem thử và seed: tránh duy trì hai bộ nội dung lệch nhau.
const catalog = JSON.parse(
  await readFile(new URL('../src/data/catalog.demo.json', import.meta.url), 'utf8'),
)
const tables = [
  'artists',
  'works',
  'work_roles',
  'media_items',
  'media_artists',
  'tracks',
  'events',
  'projects',
  'project_entries',
  'editorial_entries',
  'glossary',
  'checklist_items',
  'quiz_questions',
  'downloads',
  'jummo_fortunes',
  'jummo_secret_rewards',
]
const identifier = (value) => {
  if (!/^[a-z_]+$/.test(value)) throw new Error(`Invalid identifier: ${value}`)
  return `"${value}"`
}
const literal = (value) => {
  if (value == null) return 'NULL'
  if (Array.isArray(value)) return `ARRAY[${value.map(literal).join(',')}]::text[]`
  if (typeof value === 'boolean') return value ? 'true' : 'false'
  if (typeof value === 'number' && Number.isFinite(value)) return String(value)
  if (typeof value !== 'string') throw new Error('Unsupported seed value')
  return `'${value.replaceAll("'", "''")}'`
}
const statements = [
  '-- Generated by npm run db:seed. Dữ liệu lịch/quỹ is_demo không phải thông báo thật.',
  '-- Chạy sau 001–005. Chạy lại không ghi đè nội dung quản trị đã sửa.',
  'begin;',
  'set local standard_conforming_strings = on;',
]
for (const table of tables) {
  for (const row of catalog[table] ?? []) {
    const columns = Object.keys(row)
    statements.push(
      `insert into public.${identifier(table)} (${columns.map(identifier).join(',')}) values (${columns.map((key) => literal(row[key])).join(',')}) on conflict do nothing;`,
    )
  }
}
statements.push('commit;', '')
await writeFile(new URL('../supabase/seed.sql', import.meta.url), statements.join('\n'))
console.log('Generated supabase/seed.sql')
